# Generated by Django 3.2.14 on 2022-12-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='EMPLOYEE_INFO',
        ),
    ]
