# Generated by Django 3.2.14 on 2022-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='book',
            table='BOOK_MASTER',
        ),
    ]
